Update the build engine used by abCalc.

diff --git a/abCalc/make/orca-cc b/abCalc/make/orca-cc
--- a/abCalc/make/orca-cc
+++ b/abCalc/make/orca-cc
@@ -1,8 +1,12 @@
 #!/bin/bash
 
-TMPFILE=/tmp/orca-cc.$$
+STDOUTPUT=/tmp/orca-cc-std.$$
+ERROUTPUT=/tmp/orca-cc-errs.$$
 
 FILENAME="$1"
+shift
+
+DESTBASENAME="$1"
 shift
 
 if echo $FILENAME | grep -v '\.c$' > /dev/null
@@ -23,29 +27,53 @@ do
     fi
 done
 
-BASENAME=`echo $FILENAME | sed 's/\.c$//'`
-DEPSNAME="${BASENAME}.d"
-OBJSNAME="${BASENAME}.a"
-ROOTNAME="${BASENAME}.root"
+SRCBASENAME=`echo "$FILENAME" | sed 's/\.c$//'`
+SRCOBJNAME="${SRCBASENAME}.a"
+SRCROOTNAME="${SRCBASENAME}.root"
 
-$ORCA --trace-gsos compile $COMPILEARGS "$FILENAME" keep="${BASENAME}" $CCARGS 2> $TMPFILE
+DESTDEPSNAME="${DESTBASENAME}.d"
+DESTOBJNAME="${DESTBASENAME}.a"
+DESTROOTNAME="${DESTBASENAME}.root"
+
+$ORCA --trace-gsos compile $COMPILEARGS "$FILENAME" keep="${SRCBASENAME}" $CCARGS > $STDOUTPUT 2> $ERROUTPUT
 RESULT=$?
 
-sed '/^[A-Za-z][A-Za-z]*(.*)$/d' $TMPFILE >&2
+awk '
+    {
+        print $0
+    }
+
+    $1 ~ /^[0-9][0-9]*$/ {
+        LINENO=$1
+    }
+
+    /^ *\^/ {
+        sub(/^ *\^/, "", $0)
+        printf("%s/%s:%d:0: error: %s\n", PWD, FILE, LINENO, $0)
+    }
+' "PWD=`pwd`" "FILE=$FILENAME" $STDOUTPUT
+
+
+sed '/^[A-Za-z][A-Za-z]*(.*)$/d' $ERROUTPUT >&2
 
 if [ "$RESULT" -ne 0 ]
 then
-    rm -f $TMPFILE
-    rm -f $OBJSNAME
-    rm -f $ROOTNAME
+    rm -f $ERROUTPUT
+    rm -f $STDOUTPUT
+    rm -f $SRCOBJNAME
+    rm -f $SRCROOTNAME
     exit $RESULT
 fi
+
+mkdir -p `dirname "$DESTOBJNAME"`
+mv -f "$SRCOBJNAME" "$DESTOBJNAME" 2> /dev/null
+mv -f "$SRCROOTNAME" "$DESTROOTNAME" 2> /dev/null
 
 DEPS=`awk '
     /^FastFileLoad/ {
         sub(/^FastFileLoad\(/, "");
         sub(/\)$/, "");
-        print}' $TMPFILE | sort -u | while read FILE
+        print}' $ERROUTPUT | sort -u | while read FILE
     do
         if [ -f "$FILE" ]
         then
@@ -53,14 +81,15 @@ DEPS=`awk '
         fi
     done | tr '\012' ' '`
 
-rm -f $TMPFILE
+rm -f $ERROUTPUT
+rm -f $STDOUTPUT
 
 # We add a dependency for both the .o and the .root file.  If this is the
 # main.c file being compiled, we need the dependency on the .root file.
-cat > $DEPSNAME << EOF
-$OBJSNAME: $DEPS
+cat > $DESTDEPSNAME << EOF
+$DESTOBJNAME: $DEPS
 
-$ROOTNAME: $DEPS
+$DESTROOTNAME: $DEPS
 EOF
 
 exit 0
diff --git a/abCalc/make/orca-rez b/abCalc/make/orca-rez
--- a/abCalc/make/orca-rez
+++ b/abCalc/make/orca-rez
@@ -1,8 +1,11 @@
 #!/bin/bash
 
-TMPFILE=/tmp/orca-rez.$$
+ERROUTPUT=/tmp/orca-rez-err.$$
 
 FILENAME="$1"
+shift
+
+DESTBASENAME="$1"
 shift
 
 if echo $FILENAME | grep -v '\.rez$' > /dev/null
@@ -11,27 +14,47 @@ then
     exit 1
 fi
 
-BASENAME=`echo $FILENAME | sed 's/\.rez$//'`
-DEPSNAME="${BASENAME}.rez.d"
-OBJSNAME="${BASENAME}.r"
+SRCBASENAME=`echo $FILENAME | sed 's/\.rez$//'`
+SRCOBJNAME="${SRCBASENAME}.r"
 
-$ORCA --trace-gsos compile $* keep="${OBJSNAME}" "$FILENAME" 2> $TMPFILE
+DESTDEPSNAME="${DESTBASENAME}.rez.d"
+DESTOBJNAME="${DESTBASENAME}.r"
+
+$ORCA --trace-gsos compile "$@" keep="${SRCOBJNAME}" "$FILENAME" 2> $ERROUTPUT
 RESULT=$?
 
-sed '/^[A-Za-z][A-Za-z]*(.*)$/d' $TMPFILE >&2
+awk '
+    /^[A-Za-z][A-Za-z]*\(.*\)$/ {
+        next
+    }
+
+    {
+        print
+    }
+
+    /^File [^ ]*; Line [0-9][0-9]*;/ {
+        sub(/;/,"",$4)
+        LINENO=$4
+        sub(/^File [^ ]*; Line [0-9][0-9]*/, "", $0)
+        printf("%s/%s:%d:0: error: %s\n", PWD, FILE, LINENO, $0)
+    }
+' "PWD=`pwd`" "FILE=$FILENAME" $ERROUTPUT >&2
 
 if [ "$RESULT" -ne 0 ]
 then
-    rm -f $TMPFILE
-    rm -f $OBJSNAME
+    rm -f $ERROUTPUT
+    rm -f $SRCOBJNAME
     exit $RESULT
 fi
+
+mkdir -p `dirname "$DESTOBJNAME"`
+mv -f "$SRCOBJNAME" "$DESTOBJNAME" 2> /dev/null
 
 DEPS=`awk '
     /^FastFileLoad/ {
         sub(/^FastFileLoad\(/, "");
         sub(/\)$/, "");
-        print}' $TMPFILE | sort -u | while read FILE
+        print}' $ERROUTPUT | sort -u | while read FILE
     do
         if [ -f "$FILE" ]
         then
@@ -39,7 +62,7 @@ DEPS=`awk '
         fi
     done`
 
-echo $OBJSNAME: $DEPS > $DEPSNAME
-rm -f $TMPFILE
+echo $DESTOBJNAME: $DEPS > $DESTDEPSNAME
+rm -f $ERROUTPUT
 
 exit 0
